export const defaultCOA = [
  {
    accountCode: "10000",
    accountName: "Cash",
    classification: "Asset",
    type: "Cash",
    detailType: "Cash",
  },
  {
    accountCode: "10001",
    accountName: "Cash on Hand",
    classification: "Asset",
    type: "Cash",
    detailType: "Cash on Hand",
  },
  {
    accountCode: "10002",
    accountName: "Main Checking Account",
    classification: "Asset",
    type: "Cash",
    detailType: "Bank Account - Operating ",
  },
  {
    accountCode: "10003",
    accountName: "Savings Account",
    classification: "Asset",
    type: "Cash",
    detailType: "Bank Account - Savings",
  },
  {
    accountCode: "10100",
    accountName: "Accounts Receivable - General",
    classification: "Asset",
    type: "Accounts Receivable",
    detailType: "Accounts Receivable",
  },
  {
    accountCode: "10101",
    accountName: "Accounts Receivable - Billed",
    classification: "Asset",
    type: "Accounts Receivable",
    detailType: "Accounts Receivable",
  },
  {
    accountCode: "10102",
    accountName: "Accounts Receivable - Billed",
    classification: "Asset",
    type: "Accounts Receivable",
    detailType: "Accounts Receivable",
  },
  {
    accountCode: "10200",
    accountName: "Prepaid Expense",
    classification: "Asset",
    type: "Other Current Asset",
    detailType: "Prepaid Expense",
  },
  {
    accountCode: "10201",
    accountName: "Prepaid Rent",
    classification: "Asset",
    type: "Other Current Asset",
    detailType: "Prepaid Expense",
  },
  {
    accountCode: "10300",
    accountName: "Inventory on Hand",
    classification: "Asset",
    type: "Other Current Asset",
    detailType: "Inventory",
  },
  {
    accountCode: "10400",
    accountName: "Other Current Assets",
    classification: "Asset",
    type: "Other Current Asset",
    detailType: "Other Current Assets",
  },
  {
    accountCode: "10401",
    accountName: "Advance Payments",
    classification: "Asset",
    type: "Other Current Asset",
    detailType: "Advance Payments",
  },
  {
    accountCode: "10402",
    accountName: "Employee Loans",
    classification: "Asset",
    type: "Other Current Asset",
    detailType: "Employee Advances",
  },
  {
    accountCode: "10403",
    accountName: "Miscellaneous Receivables",
    classification: "Asset",
    type: "Other Current Asset",
    detailType: "Other Receivables",
  },
  {
    accountCode: "10404",
    accountName: "Security Deposits",
    classification: "Asset",
    type: "Other Current Asset",
    detailType: "Security Deposits",
  },
  {
    accountCode: "10500",
    accountName: "Fixed Assets",
    classification: "Asset",
    type: "Fixed Asset",
    detailType: "Fixed Assets",
  },
  {
    accountCode: "10501",
    accountName: "Vehicle",
    classification: "Asset",
    type: "Fixed Assets",
    detailType: "nan",
  },
  {
    accountCode: "10502",
    accountName: "Office Equipment",
    classification: "Asset",
    type: "Fixed Asset",
    detailType: "Office Equipment",
  },
  {
    accountCode: "10503",
    accountName: "IT Equipment",
    classification: "Asset",
    type: "Fixed Asset",
    detailType: "IT Equipment",
  },
  {
    accountCode: "10599",
    accountName: "Accumulated Depreciation - Assets",
    classification: "Asset",
    type: "Fixed Asset",
    detailType: "Accumulated Depreciation",
  },
  {
    accountCode: "20100",
    accountName: "Accounts Payable - Trade",
    classification: "Liabilities",
    type: "Accounts Payable",
    detailType: "Accounts Payable",
  },
  {
    accountCode: "20200",
    accountName: "Deferred Revenue",
    classification: "Liabilities",
    type: "Other Current Liabilities",
    detailType: "Deferred Revenue",
  },
  {
    accountCode: "20300",
    accountName: "Payroll Taxes Payable",
    classification: "Liabilities",
    type: "Other Current Liabilities",
    detailType: "Payroll Liabilities",
  },
  {
    accountCode: "20301",
    accountName: "Federal Withholding Payable",
    classification: "Liabilities",
    type: "Other Current Liabilities",
    detailType: "Payroll Liabilities",
  },
  {
    accountCode: "20302",
    accountName: "State Withholding Payable",
    classification: "Liabilities",
    type: "Other Current Liabilities",
    detailType: "Payroll Liabilities",
  },
  {
    accountCode: "20303",
    accountName: "City Taxes Payable",
    classification: "Liabilities",
    type: "Other Current Liabilities",
    detailType: "Payroll Liabilities",
  },
  {
    accountCode: "20304",
    accountName: "Employee Deductions Payable",
    classification: "Liabilities",
    type: "Other Current Liabilities",
    detailType: "Payroll Liabilities",
  },
  {
    accountCode: "20305",
    accountName: "PTO Accrual",
    classification: "Liabilities",
    type: "Other Current Liabilities",
    detailType: "Payroll Liabilities",
  },
  {
    accountCode: "20306",
    accountName: "Retirement Contributions Payable",
    classification: "Liabilities",
    type: "Other Current Liabilities",
    detailType: "Payroll Liabilities",
  },
  {
    accountCode: "20400",
    accountName: "Bank Loans Payable",
    classification: "Liabilities",
    type: "Long-Term Liabilities",
    detailType: "Bank Loans",
  },
  {
    accountCode: "20500",
    accountName: "Intercompany Payable",
    classification: "Liabilities",
    type: "Other Current Liabilities",
    detailType: "Intercompany Payable",
  },
  {
    accountCode: "30000",
    accountName: "Opening Equity Balance",
    classification: "Equity",
    type: "Equity",
    detailType: "Opening Balance Equity",
  },
  {
    accountCode: "30100",
    accountName: "Owner's Capital Account",
    classification: "Equity",
    type: "Equity",
    detailType: "Owner's Equity",
  },
  {
    accountCode: "30200",
    accountName: "Common Stock",
    classification: "Equity",
    type: "Equity",
    detailType: "Common Stock",
  },
  {
    accountCode: "30300",
    accountName: "Retained Income",
    classification: "Equity",
    type: "Equity",
    detailType: "Retained Earnings",
  },
  {
    accountCode: "40100",
    accountName: "Revenue from Services",
    classification: "Revenue",
    type: "Income",
    detailType: "Service Revenue",
  },
  {
    accountCode: "40200",
    accountName: "Revenue from Products",
    classification: "Revenue",
    type: "Income",
    detailType: "Product Revenue",
  },
  {
    accountCode: "40300",
    accountName: "Deferred Revenue",
    classification: "Revenue",
    type: "Income",
    detailType: "Deferred Revenue",
  },
  {
    accountCode: "50000",
    accountName: "Cost of Goods Sold",
    classification: "COGS",
    type: "Cost of Goods Sold",
    detailType: "COGS",
  },
  {
    accountCode: "50100",
    accountName: "Labor Costs - Direct",
    classification: "COGS",
    type: "Cost of Goods Sold",
    detailType: "Direct Labor",
  },
  {
    accountCode: "50200",
    accountName: "Subcontractor Costs",
    classification: "COGS",
    type: "Cost of Goods Sold",
    detailType: "Subcontractors",
  },
  {
    accountCode: "50300",
    accountName: "Manufacturing Supplies",
    classification: "COGS",
    type: "Cost of Goods Sold",
    detailType: "Supplies",
  },
  {
    accountCode: "50400",
    accountName: "Packaging Materials",
    classification: "COGS",
    type: "Cost of Goods Sold",
    detailType: "Materials",
  },
  {
    accountCode: "50500",
    accountName: "Travel Expenses - Direct",
    classification: "COGS",
    type: "Cost of Goods Sold",
    detailType: "Travel Expenses",
  },
  {
    accountCode: "50501",
    accountName: "Lodging Expenses",
    classification: "COGS",
    type: "Cost of Goods Sold",
    detailType: "Lodging",
  },
  {
    accountCode: "50502",
    accountName: "Transportation",
    classification: "COGS",
    type: "Cost of Goods Sold",
    detailType: "Transportation",
  },
  {
    accountCode: "50503",
    accountName: "Fuel Reimbursements",
    classification: "COGS",
    type: "Cost of Goods Sold",
    detailType: "Fuel Reimbursements",
  },
  {
    accountCode: "50504",
    accountName: "Business Meals - Direct",
    classification: "COGS",
    type: "Cost of Goods Sold",
    detailType: "Meals",
  },
  {
    accountCode: "50505",
    accountName: "Airfare Expenses",
    classification: "COGS",
    type: "Cost of Goods Sold",
    detailType: "Airfare",
  },
  {
    accountCode: "50506",
    accountName: "Car Rentals",
    classification: "COGS",
    type: "Cost of Goods Sold",
    detailType: "Car Rentals",
  },
  {
    accountCode: "50600",
    accountName: "Miscellaneous Direct Costs",
    classification: "COGS",
    type: "Cost of Goods Sold",
    detailType: "Miscellaneous Costs",
  },
  {
    accountCode: "60000",
    accountName: "Employee Benefits",
    classification: "Expense",
    type: "Expense",
    detailType: "Employee Benefits",
  },
  {
    accountCode: "60100",
    accountName: "Health Insurance Premiums",
    classification: "Expense",
    type: "Expense",
    detailType: "Health Insurance",
  },
  {
    accountCode: "60101",
    accountName: "Dental Insurance Premiums",
    classification: "Expense",
    type: "Expense",
    detailType: "Dental Insurance",
  },
  {
    accountCode: "60200",
    accountName: "Retirement Plan Contributions",
    classification: "Expense",
    type: "Expense",
    detailType: "Retirement Contributions",
  },
  {
    accountCode: "60300",
    accountName: "Workers' Comp Insurance",
    classification: "Expense",
    type: "Expense",
    detailType: "Workers' Compensation",
  },
  {
    accountCode: "60400",
    accountName: "Employer Payroll Taxes",
    classification: "Expense",
    type: "Expense",
    detailType: "Payroll Taxes",
  },
  {
    accountCode: "70000",
    accountName: "Overhead",
    classification: "Expense",
    type: "Expense",
    detailType: "Overhead",
  },
  {
    accountCode: "70100",
    accountName: "Office Rent",
    classification: "Expense",
    type: "Expense",
    detailType: "Office Rent",
  },
  {
    accountCode: "70101",
    accountName: "Utility Bills",
    classification: "Expense",
    type: "Expense",
    detailType: "Utilities",
  },
  {
    accountCode: "70102",
    accountName: "Building Maintenance",
    classification: "Expense",
    type: "Expense",
    detailType: "Maintenance",
  },
  {
    accountCode: "70200",
    accountName: "Printing and Stationery",
    classification: "Expense",
    type: "Expense",
    detailType: "Printing and Stationery",
  },
  {
    accountCode: "70201",
    accountName: "Office Supplies",
    classification: "Expense",
    type: "Expense",
    detailType: "Office Supplies",
  },
  {
    accountCode: "70202",
    accountName: "Telephone and Internet",
    classification: "Expense",
    type: "Expense",
    detailType: "Communications",
  },
  {
    accountCode: "70300",
    accountName: "Technology Subscriptions",
    classification: "Expense",
    type: "Expense",
    detailType: "Technology Subscriptions",
  },
  {
    accountCode: "70400",
    accountName: "Depreciation Expenses",
    classification: "Expense",
    type: "Expense",
    detailType: "Depreciation",
  },
  {
    accountCode: "80000",
    accountName: "General Administrative Expenses",
    classification: "Expense",
    type: "Expense",
    detailType: "Administrative Expenses",
  },
  {
    accountCode: "80100",
    accountName: "Administrative Wages",
    classification: "Expense",
    type: "Expense",
    detailType: "Wages",
  },
  {
    accountCode: "80200",
    accountName: "Staff Training and Development",
    classification: "Expense",
    type: "Expense",
    detailType: "Training",
  },
  {
    accountCode: "80300",
    accountName: "Recruitment Costs",
    classification: "Expense",
    type: "Expense",
    detailType: "Recruitment",
  },
  {
    accountCode: "80400",
    accountName: "Professional Services",
    classification: "Expense",
    type: "Expense",
    detailType: "Professional Fees",
  },
  {
    accountCode: "88000",
    accountName: "Marketing and Advertising",
    classification: "Expense",
    type: "Expense",
    detailType: "Marketing",
  },
  {
    accountCode: "88100",
    accountName: "Online Advertising",
    classification: "Expense",
    type: "Expense",
    detailType: "Advertising",
  },
  {
    accountCode: "88200",
    accountName: "Event Sponsorship",
    classification: "Expense",
    type: "Expense",
    detailType: "Event Sponsorship",
  },
  {
    accountCode: "88300",
    accountName: "Print Marketing",
    classification: "Expense",
    type: "Expense",
    detailType: "Marketing",
  },
  {
    accountCode: "88400",
    accountName: "Social Media Marketing",
    classification: "Expense",
    type: "Expense",
    detailType: "Social Media",
  },
  {
    accountCode: "88500",
    accountName: "Website Hosting",
    classification: "Expense",
    type: "Expense",
    detailType: "Hosting",
  },
  {
    accountCode: "90000",
    accountName: "Miscellaneous Expenses",
    classification: "Expense",
    type: "Expense",
    detailType: "Miscellaneous",
  },
  {
    accountCode: "90100",
    accountName: "Unallowable Business Costs",
    classification: "Expense",
    type: "Expense",
    detailType: "Unallowable Costs",
  },
  {
    accountCode: "90200",
    accountName: "Legal Penalties",
    classification: "Expense",
    type: "Expense",
    detailType: "Penalties",
  },
  {
    accountCode: "90300",
    accountName: "Bank Fees",
    classification: "Expense",
    type: "Expense",
    detailType: "Bank Fees",
  },
  {
    accountCode: "90400",
    accountName: "Interest Charges",
    classification: "Expense",
    type: "Expense",
    detailType: "Interest",
  },
  {
    accountCode: "90500",
    accountName: "Donations and Contributions",
    classification: "Expense",
    type: "Expense",
    detailType: "Donations",
  },
  {
    accountCode: "98000",
    accountName: "Other Income",
    classification: "Other",
    type: "Other Income",
    detailType: "Miscellaneous Income",
  },
  {
    accountCode: "98100",
    accountName: "Dividend Income",
    classification: "Other",
    type: "Other Income",
    detailType: "Dividends",
  },
  {
    accountCode: "98200",
    accountName: "Investment Gains",
    classification: "Other",
    type: "Other Income",
    detailType: "Investments",
  },
  {
    accountCode: "98300",
    accountName: "Other Expenses",
    classification: "Other",
    type: "Other Expenses",
    detailType: "Other Expenses",
  },
];
